"""initial schema

Revision ID: 8d6511b88944
Revises: 
Create Date: 2026-08-16 00:10:52.762804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6511b88944'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=False),
    sa.Column('intern_id', sa.String(length=20), nullable=True),
    sa.Column('internship_role', sa.String(length=100), nullable=True),
    sa.Column('referral_person', sa.String(length=100), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('linkedin', sa.String(length=255), nullable=True),
    sa.Column('github', sa.String(length=255), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_group', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('mentor', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('work_year', sa.String(length=20), nullable=True),
    sa.Column('work_domain', sa.String(length=100), nullable=True),
    sa.Column('responsibilities', sa.String(length=500), nullable=True),
    sa.Column('work_information', sa.String(length=1000), nullable=True),
    sa.Column('present_days', sa.Integer(), nullable=True),
    sa.Column('absent_days', sa.Integer(), nullable=True),
    sa.Column('leave_days', sa.Integer(), nullable=True),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('holidays', sa.Integer(), nullable=True),
    sa.Column('attendance_percentage', sa.Float(), nullable=True),
    sa.Column('offer_letter', sa.String(length=255), nullable=True),
    sa.Column('acknowledgement_letter', sa.String(length=255), nullable=True),
    sa.Column('terms_conditions', sa.String(length=255), nullable=True),
    sa.Column('lor', sa.String(length=255), nullable=True),
    sa.Column('completion_letter', sa.String(length=255), nullable=True),
    sa.Column('certificate', sa.String(length=255), nullable=True),
    sa.Column('resume', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('intern_id')
    )
    op.create_index(op.f('ix_interns_id'), 'interns', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intern_id', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['intern_id'], ['interns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intern_id', sa.Integer(), nullable=False),
    sa.Column('appointment_letter', sa.String(length=255), nullable=True),
    sa.Column('offer_letter', sa.String(length=255), nullable=True),
    sa.Column('transfer_certificate', sa.String(length=255), nullable=True),
    sa.Column('other_document', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['intern_id'], ['interns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('lors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intern_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('issued_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['intern_id'], ['interns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lors_id'), 'lors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lors_id'), table_name='lors')
    op.drop_table('lors')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_interns_id'), table_name='interns')
    op.drop_table('interns')
    # ### end Alembic commands ###
